---
- name: ansible playbook to test ansible vault
  hosts: all
  become: true
  vars_files:
    - vault-pass.yml
  tasks:
  - name: clone a repo
    git:
      repo: https://mun..:{{ password }}github.com/muneendra001/vault.git  # Here we r giving github username.password sending as variable,the password should be present in vault-pass.yml file. ##may be this old method
      dest: /opt/ansadmin/test-vault
        # accept_hostkey: yes  # may be New method
        #key_file: /home/ansadmin/.ssh/authorized_keys
