---
- name: This playbook to creates a directory
  hosts: all
  #become: true
  tasks:
  - name: creating a dir
    file:
      path: /home/ansadmin/demo
      state: directory


# If we mention become=true,then file,dir ownership (created) as a root user
# first it logined as a ansadmin then file created as a root user.
