---
- name: This playbook to creates a file
  hosts: all
  become: true
  tasks:
  - name: creating a file
    file:
      path: /home/ansadmin/demofile.txt
      state: touch


# If we mention become=true,then file ownership (created) as a root user
# first it logined as a ansadmin then file created as a root user.
