---
- name: This playbook install httpd
  hosts: webservers
  become: true
  tasks:  #each hypen(-) represents a one task
  - name: installing httpd  package
    yum:
      name: httpd
      state: installed    #when it is installed then it inform notify to do action,then notify sends order to handlers to perform action.the notify statement and handlers name statement should be the same.
    notify: start httpd service

  handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
