---
- name: This playbook to install httpd and apache2
  hosts: all
  become: true
  tasks:  #each hypen(-) represents a one task
  - name: installing httpd  package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes  # Ignore errors will not discontinue the process if any task gots error,it will go further and executes all tasks. 

  - name: installing apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copying index.html  # This task is to copy index.html from from control node to target servers httpd deployment location.
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
