---
- name: This playbook to install httpd and apache2
  hosts: all
  become: true
  tasks:  #each hypen(-) represents a one task
  - name: installing httpd  package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    tags: install_apache

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    tags: start_apache

  - name: installing apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: install_apache

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
    tags: start_apache        # Tags are used to perform a particular tasks.

  - name: copying index.html  # This task is to copy index.html from from control node to target servers httpd deployment location.
    copy:
      src: /opt/ansible/index.html  # Here this task executes only if we execute the playbook without tags,bcoz we didn't mentioned any tags to this task.
      dest: /var/www/html
      mode: 0666
