---
- name: This playbook install httpd
  hosts: webservers
  become: true
  tasks:  #each hypen(-) represents a one task
  - name: installing httpd  package
    yum:
      name: httpd
      state: installed
  - name: start httpd service
    service:
      name: httpd
      state: started
