---
- name: ansible playbook to setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name : download tomcat packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.83/bin/apache-tomcat-9.0.83.tar.gz
      dest: /opt

  - name: untar apache packages
    unarchive:
      src: /opt/apache-tomcat-9.0.83.tar.gz
      dest: /opt
      remote_src: yes  # This is to say apache-tomcat-9.0.83.tar.gz file in the target server,not in the control node.

  - name: add execution permissions on startup.sh file
    file:
      path: /opt/apache-tomcat-9.0.83/bin/startup.sh
      mode: 0777

  - name: start tomcat services # shell module to execute shell commands on targets.
    shell : nohup ./startup.sh   # nohup is to run script startup.sh continuosly in background.
    args:
      chdir: /opt/apache-tomcat-9.0.83/bin  # chdir to change directory to this /opt/apache-tomcat-9.0.83/bin directory before running the command. 
