---
- name: This playbook uninstall httpd
  hosts: webservers
  become: true
  tasks:  #each hypen(-) represents a one task
  - name: stop httpd service
    service:
      name: httpd
      state: stopped
  - name: uninstalling httpd  package
    yum:
      name: httpd
      state: removed
