---
- name: This playbook to uninstall httpd and apache2
  hosts: all
  become: true
  tasks:  #each hypen(-) represents a one task
  - name: stop httpd service
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: uninstalling httpd  package
    yum:
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"

  - name: stop apache2 service
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: uninstalling apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
